export interface ICurrency {
    rates: {
        CAD: number,
        USD: number,
        EUR: number,
        HKD: number,
        ISK: number,
        CHF: number,
        DKK: number,
        HUF: number,
        CZK: number,
        GBP: number,
        RON: number,
        SEK: number,
        IDR: number,
        INR: number,
        BRL: number,
        RUB: number,
        HRK: number,
        JPY: number,
        THB: number,
        MYR: number,
        BGN: number,
        TRY: number,
        CNY: number,
        NOK: number,
        NZD: number,
        ZAR: number,
        MXN: number,
        SGD: number,
        AUD: number,
        ILS: number,
        KRW: number,
        PLN: number,

    }
}